version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=kiumars
      - RABBITMQ_DEFAULT_PASS=1975kj1975
    volumes:
        - rabbitmq-data/:/var/lib/rabbitmq/
        - rabbitmq-log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net

volumes:
  rabbitmq-data:
  rabbitmq-log:
networks:
  rabbitmq_go_net:
    driver: bridge