"""empty message

Revision ID: 2ea4cd48e964
Revises: 2a458d98558e
Create Date: 2023-03-22 09:26:28.521608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ea4cd48e964'
down_revision = '2a458d98558e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fullname', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('username', sa.String(length=64), nullable=True))
        batch_op.drop_index('ix_student_name')
        batch_op.create_index(batch_op.f('ix_student_fullname'), ['fullname'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_username'), ['username'], unique=True)
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_student_username'))
        batch_op.drop_index(batch_op.f('ix_student_fullname'))
        batch_op.create_index('ix_student_name', ['name'], unique=False)
        batch_op.drop_column('username')
        batch_op.drop_column('fullname')

    # ### end Alembic commands ###
